In [51]:
library(readr)
df <- read_csv("combined_data.csv")
head(df)

Rows: 10771 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (6): Car Model, Condition, Mileage, Price (USD), Monthly Payment, Dealer...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  Car Model                                              Condition Mileage
1 2023 BMW M2 Base                                       Used      2,496 mi.
2 2020 Dodge Charger SXT                                 Used      98,302 mi.
3 2016 Scion iM Base                                     Used      72,040 mi.
4 2022 Volvo XC60 Recharge Plug-In Hybrid T8 Inscription Used      31,580 mi.
5 2012 Mitsubishi Lancer SE                              Used      54,197 mi.
6 2023 Chevrolet Bolt EUV FWD LT                         Used      19,045 mi.
  Price (USD) Monthly Payment Dealer Name
1 $63,000     Est. $1,184/mo  Murgado Ford of Chicago
2 $14,995     Est. $282/mo    Blue Sky Auto Sales - Brighton Park
3 $12,690     Est. $239/mo    Mcgrath Evanston Subaru
4 $38,998     Est. $733/mo    CarMax Birmingham
5 $9,995      Est. $188/mo    Moto Zone Inc.
6 $18,995     Est. $357/mo    Luxury Motors Credit

In [ ]:
#Подсчет пропусков
colSums(is.na(df))

      Car Model       Condition         Mileage     Price (USD) Monthly Payment
              0              28            5143               0             200
    Dealer Name
              0

In [53]:
#Удалим пропуски
df$Condition[is.na(df$Condition)] = "Unknown"
df = filter(df,!is.na(Mileage))
df = filter(df,!is.na(`Monthly Payment`))

In [ ]:
#Удаление дубликатов
df = df[!duplicated(df), ]
print("Дубликаты удалены.")

[1] "Дубликаты удалены."

In [ ]:
#Преобразование типа
df$`Price (USD)` = as.numeric(gsub("[\\$,]", "", df$`Price (USD)`))

In [56]:
head(df)

  Car Model                                              Condition Mileage
1 2023 BMW M2 Base                                       Used      2,496 mi.
2 2020 Dodge Charger SXT                                 Used      98,302 mi.
3 2016 Scion iM Base                                     Used      72,040 mi.
4 2022 Volvo XC60 Recharge Plug-In Hybrid T8 Inscription Used      31,580 mi.
5 2012 Mitsubishi Lancer SE                              Used      54,197 mi.
6 2023 Chevrolet Bolt EUV FWD LT                         Used      19,045 mi.
  Price (USD) Monthly Payment Dealer Name
1 63000       Est. $1,184/mo  Murgado Ford of Chicago
2 14995       Est. $282/mo    Blue Sky Auto Sales - Brighton Park
3 12690       Est. $239/mo    Mcgrath Evanston Subaru
4 38998       Est. $733/mo    CarMax Birmingham
5  9995       Est. $188/mo    Moto Zone Inc.
6 18995       Est. $357/mo    Luxury Motors Credit